### ISSUE TITLE
Proposed DB Schema

### ISSUE THREAD

**Issue by Trekkan** [CatalysmsServerManager/Global-ban-list#4]
This isn't 100% fleshed out, but I think the DB schema needs to be more defined before things are built.  This also helps define the feature sets now, instead of later down the road, causing breaking schema changes.

Please let me know if this is a direction people are interested in as well as add to it, modify it, etc.  Or, just ignore it. ;)

Users (users that are able to use the GBL)
	id
	username
	name
	email
	lastVisited
	guid (Private key, used in combination with the servers GUID for creating/removing bans)
	
Servers (Servers that have signed up for the GBL)
	id
	userId (foreign key to Users)
	guid (Private key the servers send when creating/removing a ban)

Apps (A list of games, so the GBL can be used for more than just 7d2d if desired)
	id
	name
	
Players (list of banned players)
	id
	steamId
	name
	
BanReasons (list of ban reasons, reason = short description, reasonDesc = long description)
	id
	reason
	reasonDesc	

Bans
	id (autoinc Id)
	appId (foreign key to apps)
	serverId (foreign key to Servers)
	playerId (foreign key to Players)
	reasonId (foreign key to BanReasons)
	status (Active, Removed, Elapsed)
	bannedBy (Name of admin who banned the player)
	bannedUntil
	removedBy (Name of admin who removed the ban)
	removedOn (Date ban was removed)

**Comment by niekcandaele** [comment]
I've implemented this stuff and some more. I'll close this issue, if you have any additional suggestions, feel free to create a new one :).
